[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "npm install",
    "python3 -m pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = "node bot.js"
