[phases.setup]
nixPkgs = ["nodejs", "python3"]

[phases.install]
cmds = [
    "npm install",
    "python3 -m venv /app/venv",
    "/app/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "node bot.js"
